version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: workshop-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: workshop_board
    volumes:
      - mongodb_data:/data/db
    networks:
      - workshop-network

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:1.0.2
    container_name: workshop-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - workshop-network

volumes:
  mongodb_data:

networks:
  workshop-network:
    driver: bridge
